/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.   ### HTTP status codes  All error responses use the `LedgerResponse` envelope (`code`, `type`, `message`, `responseDateTime`, optional `resourceUri`).  | Status | `type` | When | |--------|--------|------| | `400` | `Bad Request` | Malformed request, missing required fields, or invalid field values | | `401` | `Unauthorized` | Missing or invalid credentials | | `404` | `Not Found` | Resource does not exist or caller lacks access | | `409` | `Conflict` | Concurrent or competing update to the same resource (for example, two operations racing to mutate the same loan while both appear valid in isolation) | | `422` | `Unprocessable Entity` | Request is syntactically valid but cannot be applied to the resource in its current state (for example, `POST .../decline` when `loanStatus` is not `PROPOSED`) | | `500` | `Error` | Unexpected server failure |  **State transitions vs. conflicts:** lifecycle operations (`approve`, `decline`, `cancel`, `unwind`, and similar) return **`422`** when the action is not permitted for the resource's current status. Message example: `Invalid action for current loan status`. Reserve **`409`** for true resource conflicts such as optimistic-concurrency failures when parallel clients attempt incompatible updates.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.3.1
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.model;

import java.io.Serializable;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CollateralAmendment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-09T19:15:38.929307762Z[GMT]")

public class CollateralAmendment implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("collateralCurrency")
  private CurrencyCd collateralCurrency = null;

  @SerializedName("collateralMargin")
  private Double collateralMargin = null;

  @SerializedName("roundingRule")
  private Integer roundingRule = null;

  @SerializedName("roundingMode")
  private RoundingMode roundingMode = null;

  @SerializedName("minimumMarkPrice")
  private Double minimumMarkPrice = null;

  public CollateralAmendment collateralCurrency(CurrencyCd collateralCurrency) {
    this.collateralCurrency = collateralCurrency;
    return this;
  }

   /**
   * Get collateralCurrency
   * @return collateralCurrency
  **/
  @Schema(description = "")
  public CurrencyCd getCollateralCurrency() {
    return collateralCurrency;
  }

  public void setCollateralCurrency(CurrencyCd collateralCurrency) {
    this.collateralCurrency = collateralCurrency;
  }

  public CollateralAmendment collateralMargin(Double collateralMargin) {
    this.collateralMargin = collateralMargin;
    return this;
  }

   /**
   * Get collateralMargin
   * @return collateralMargin
  **/
  @Schema(description = "")
  public Double getCollateralMargin() {
    return collateralMargin;
  }

  public void setCollateralMargin(Double collateralMargin) {
    this.collateralMargin = collateralMargin;
  }

  public CollateralAmendment roundingRule(Integer roundingRule) {
    this.roundingRule = roundingRule;
    return this;
  }

   /**
   * Get roundingRule
   * @return roundingRule
  **/
  @Schema(description = "")
  public Integer getRoundingRule() {
    return roundingRule;
  }

  public void setRoundingRule(Integer roundingRule) {
    this.roundingRule = roundingRule;
  }

  public CollateralAmendment roundingMode(RoundingMode roundingMode) {
    this.roundingMode = roundingMode;
    return this;
  }

   /**
   * Get roundingMode
   * @return roundingMode
  **/
  @Schema(description = "")
  public RoundingMode getRoundingMode() {
    return roundingMode;
  }

  public void setRoundingMode(RoundingMode roundingMode) {
    this.roundingMode = roundingMode;
  }

  public CollateralAmendment minimumMarkPrice(Double minimumMarkPrice) {
    this.minimumMarkPrice = minimumMarkPrice;
    return this;
  }

   /**
   * Get minimumMarkPrice
   * @return minimumMarkPrice
  **/
  @Schema(description = "")
  public Double getMinimumMarkPrice() {
    return minimumMarkPrice;
  }

  public void setMinimumMarkPrice(Double minimumMarkPrice) {
    this.minimumMarkPrice = minimumMarkPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CollateralAmendment collateralAmendment = (CollateralAmendment) o;
    return Objects.equals(this.collateralCurrency, collateralAmendment.collateralCurrency) &&
        Objects.equals(this.collateralMargin, collateralAmendment.collateralMargin) &&
        Objects.equals(this.roundingRule, collateralAmendment.roundingRule) &&
        Objects.equals(this.roundingMode, collateralAmendment.roundingMode) &&
        Objects.equals(this.minimumMarkPrice, collateralAmendment.minimumMarkPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collateralCurrency, collateralMargin, roundingRule, roundingMode, minimumMarkPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollateralAmendment {\n");
    
    sb.append("    collateralCurrency: ").append(toIndentedString(collateralCurrency)).append("\n");
    sb.append("    collateralMargin: ").append(toIndentedString(collateralMargin)).append("\n");
    sb.append("    roundingRule: ").append(toIndentedString(roundingRule)).append("\n");
    sb.append("    roundingMode: ").append(toIndentedString(roundingMode)).append("\n");
    sb.append("    minimumMarkPrice: ").append(toIndentedString(minimumMarkPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
