/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.model;

import java.io.Serializable;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * LoanSplitLot
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-12-06T16:12:41.344560814Z[GMT]")

public class LoanSplitLot implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("loanId")
  private String loanId = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("internalRefId")
  private String internalRefId = null;

  @SerializedName("settlement")
  private PartySettlementInstruction settlement = null;

  public LoanSplitLot loanId(String loanId) {
    this.loanId = loanId;
    return this;
  }

   /**
   * Get loanId
   * @return loanId
  **/
  @Schema(description = "")
  public String getLoanId() {
    return loanId;
  }

  public void setLoanId(String loanId) {
    this.loanId = loanId;
  }

  public LoanSplitLot quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(required = true, description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public LoanSplitLot internalRefId(String internalRefId) {
    this.internalRefId = internalRefId;
    return this;
  }

   /**
   * Get internalRefId
   * @return internalRefId
  **/
  @Schema(description = "")
  public String getInternalRefId() {
    return internalRefId;
  }

  public void setInternalRefId(String internalRefId) {
    this.internalRefId = internalRefId;
  }

  public LoanSplitLot settlement(PartySettlementInstruction settlement) {
    this.settlement = settlement;
    return this;
  }

   /**
   * Get settlement
   * @return settlement
  **/
  @Schema(description = "")
  public PartySettlementInstruction getSettlement() {
    return settlement;
  }

  public void setSettlement(PartySettlementInstruction settlement) {
    this.settlement = settlement;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanSplitLot loanSplitLot = (LoanSplitLot) o;
    return Objects.equals(this.loanId, loanSplitLot.loanId) &&
        Objects.equals(this.quantity, loanSplitLot.quantity) &&
        Objects.equals(this.internalRefId, loanSplitLot.internalRefId) &&
        Objects.equals(this.settlement, loanSplitLot.settlement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loanId, quantity, internalRefId, settlement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanSplitLot {\n");
    
    sb.append("    loanId: ").append(toIndentedString(loanId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    internalRefId: ").append(toIndentedString(internalRefId)).append("\n");
    sb.append("    settlement: ").append(toIndentedString(settlement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
