/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.   ### HTTP status codes  All error responses use the `LedgerResponse` envelope (`code`, `type`, `message`, `responseDateTime`, optional `resourceUri`).  | Status | `type` | When | |--------|--------|------| | `400` | `Bad Request` | Malformed request, missing required fields, or invalid field values | | `401` | `Unauthorized` | Missing or invalid credentials | | `404` | `Not Found` | Resource does not exist or caller lacks access | | `409` | `Conflict` | Concurrent or competing update to the same resource (for example, two operations racing to mutate the same loan while both appear valid in isolation) | | `422` | `Unprocessable Entity` | Request is syntactically valid but cannot be applied to the resource in its current state (for example, `POST .../decline` when `loanStatus` is not `PROPOSED`) | | `500` | `Error` | Unexpected server failure |  **State transitions vs. conflicts:** lifecycle operations (`approve`, `decline`, `cancel`, `unwind`, and similar) return **`422`** when the action is not permitted for the resource's current status. Message example: `Invalid action for current loan status`. Reserve **`409`** for true resource conflicts such as optimistic-concurrency failures when parallel clients attempt incompatible updates.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.3.1
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.model;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Price is ignored for trade agreements and loan proposals
 */
@Schema(description = "Price is ignored for trade agreements and loan proposals")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-09T19:15:38.929307762Z[GMT]")

public class Price implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("value")
  private Double value = null;

  @SerializedName("currency")
  private CurrencyCd currency = null;

  @SerializedName("priceBasis")
  private PriceBasis priceBasis = null;

  @SerializedName("valueDate")
  private LocalDate valueDate = null;

  @SerializedName("source")
  private PriceSource source = null;

  public Price value(Double value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(required = true, description = "")
  public Double getValue() {
    return value;
  }

  public void setValue(Double value) {
    this.value = value;
  }

  public Price currency(CurrencyCd currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(required = true, description = "")
  public CurrencyCd getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyCd currency) {
    this.currency = currency;
  }

  public Price priceBasis(PriceBasis priceBasis) {
    this.priceBasis = priceBasis;
    return this;
  }

   /**
   * Get priceBasis
   * @return priceBasis
  **/
  @Schema(description = "")
  public PriceBasis getPriceBasis() {
    return priceBasis;
  }

  public void setPriceBasis(PriceBasis priceBasis) {
    this.priceBasis = priceBasis;
  }

  public Price valueDate(LocalDate valueDate) {
    this.valueDate = valueDate;
    return this;
  }

   /**
   * Get valueDate
   * @return valueDate
  **/
  @Schema(description = "")
  public LocalDate getValueDate() {
    return valueDate;
  }

  public void setValueDate(LocalDate valueDate) {
    this.valueDate = valueDate;
  }

  public Price source(PriceSource source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @Schema(description = "")
  public PriceSource getSource() {
    return source;
  }

  public void setSource(PriceSource source) {
    this.source = source;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Price price = (Price) o;
    return Objects.equals(this.value, price.value) &&
        Objects.equals(this.currency, price.currency) &&
        Objects.equals(this.priceBasis, price.priceBasis) &&
        Objects.equals(this.valueDate, price.valueDate) &&
        Objects.equals(this.source, price.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, currency, priceBasis, valueDate, source);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Price {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    priceBasis: ").append(toIndentedString(priceBasis)).append("\n");
    sb.append("    valueDate: ").append(toIndentedString(valueDate)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
