/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.2.2
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.model;

import java.io.Serializable;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ReturnPartyInternalReference
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-29T19:02:50.865809907Z[GMT]")

public class ReturnPartyInternalReference implements Serializable{
  private static final long serialVersionUID = 1L;
  @SerializedName("partyRole")
  private PartyRole partyRole = null;

  @SerializedName("returnInternalReference")
  private String returnInternalReference = null;

  public ReturnPartyInternalReference partyRole(PartyRole partyRole) {
    this.partyRole = partyRole;
    return this;
  }

   /**
   * Get partyRole
   * @return partyRole
  **/
  @Schema(description = "")
  public PartyRole getPartyRole() {
    return partyRole;
  }

  public void setPartyRole(PartyRole partyRole) {
    this.partyRole = partyRole;
  }

  public ReturnPartyInternalReference returnInternalReference(String returnInternalReference) {
    this.returnInternalReference = returnInternalReference;
    return this;
  }

   /**
   * Get returnInternalReference
   * @return returnInternalReference
  **/
  @Schema(description = "")
  public String getReturnInternalReference() {
    return returnInternalReference;
  }

  public void setReturnInternalReference(String returnInternalReference) {
    this.returnInternalReference = returnInternalReference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnPartyInternalReference returnPartyInternalReference = (ReturnPartyInternalReference) o;
    return Objects.equals(this.partyRole, returnPartyInternalReference.partyRole) &&
        Objects.equals(this.returnInternalReference, returnPartyInternalReference.returnInternalReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyRole, returnInternalReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnPartyInternalReference {\n");
    
    sb.append("    partyRole: ").append(toIndentedString(partyRole)).append("\n");
    sb.append("    returnInternalReference: ").append(toIndentedString(returnInternalReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
