/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.   ### HTTP status codes  All error responses use the `LedgerResponse` envelope (`code`, `type`, `message`, `responseDateTime`, optional `resourceUri`).  | Status | `type` | When | |--------|--------|------| | `400` | `Bad Request` | Malformed request, missing required fields, or invalid field values | | `401` | `Unauthorized` | Missing or invalid credentials | | `404` | `Not Found` | Resource does not exist or caller lacks access | | `409` | `Conflict` | Concurrent or competing update to the same resource (for example, two operations racing to mutate the same loan while both appear valid in isolation) | | `422` | `Unprocessable Entity` | Request is syntactically valid but cannot be applied to the resource in its current state (for example, `POST .../decline` when `loanStatus` is not `PROPOSED`) | | `500` | `Error` | Unexpected server failure |  **State transitions vs. conflicts:** lifecycle operations (`approve`, `decline`, `cancel`, `unwind`, and similar) return **`422`** when the action is not permitted for the resource's current status. Message example: `Invalid action for current loan status`. Reserve **`409`** for true resource conflicts such as optimistic-concurrency failures when parallel clients attempt incompatible updates.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.3.1
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.invoker.auth;

import java.util.List;
import java.util.Map;

import com.os.client.invoker.Pair;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-09-09T19:15:38.929307762Z[GMT]")
public class ApiKeyAuth implements Authentication {
  private final String location;
  private final String paramName;

  private String apiKey;
  private String apiKeyPrefix;

  public ApiKeyAuth(String location, String paramName) {
    this.location = location;
    this.paramName = paramName;
  }

  public String getLocation() {
    return location;
  }

  public String getParamName() {
    return paramName;
  }

  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public String getApiKeyPrefix() {
    return apiKeyPrefix;
  }

  public void setApiKeyPrefix(String apiKeyPrefix) {
    this.apiKeyPrefix = apiKeyPrefix;
  }

  @Override
  public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams) {
    if (apiKey == null) {
      return;
    }
    String value;
    if (apiKeyPrefix != null) {
      value = apiKeyPrefix + " " + apiKey;
    } else {
      value = apiKey;
    }
    if ("query".equals(location)) {
      queryParams.add(new Pair(paramName, value));
    } else if ("header".equals(location)) {
      headerParams.put(paramName, value);
    }
  }
}
