/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.   ### HTTP status codes  All error responses use the `LedgerResponse` envelope (`code`, `type`, `message`, `responseDateTime`, optional `resourceUri`).  | Status | `type` | When | |--------|--------|------| | `400` | `Bad Request` | Malformed request, missing required fields, or invalid field values | | `401` | `Unauthorized` | Missing or invalid credentials | | `404` | `Not Found` | Resource does not exist or caller lacks access | | `409` | `Conflict` | Concurrent or competing update to the same resource (for example, two operations racing to mutate the same loan while both appear valid in isolation) | | `422` | `Unprocessable Entity` | Request is syntactically valid but cannot be applied to the resource in its current state (for example, `POST .../decline` when `loanStatus` is not `PROPOSED`) | | `500` | `Error` | Unexpected server failure |  **State transitions vs. conflicts:** lifecycle operations (`approve`, `decline`, `cancel`, `unwind`, and similar) return **`422`** when the action is not permitted for the resource's current status. Message example: `Invalid action for current loan status`. Reserve **`409`** for true resource conflicts such as optimistic-concurrency failures when parallel clients attempt incompatible updates.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.3.1
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.invoker;

import java.util.List;
import java.util.Map;

/**
 * API response returned by API call.
 *
 * @param <T> The type of data that is deserialized from response body
 */
public class ApiResponse<T> {
    final private int statusCode;
    final private Map<String, List<String>> headers;
    final private T data;

    /**
     * @param statusCode The status code of HTTP response
     * @param headers The headers of HTTP response
     */
    public ApiResponse(int statusCode, Map<String, List<String>> headers) {
        this(statusCode, headers, null);
    }

    /**
     * @param statusCode The status code of HTTP response
     * @param headers The headers of HTTP response
     * @param data The object deserialized from response bod
     */
    public ApiResponse(int statusCode, Map<String, List<String>> headers, T data) {
        this.statusCode = statusCode;
        this.headers = headers;
        this.data = data;
    }

    public int getStatusCode() {
        return statusCode;
    }

    public Map<String, List<String>> getHeaders() {
        return headers;
    }

    public T getData() {
        return data;
    }
}
