/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.   ### HTTP status codes  All error responses use the `LedgerResponse` envelope (`code`, `type`, `message`, `responseDateTime`, optional `resourceUri`).  | Status | `type` | When | |--------|--------|------| | `400` | `Bad Request` | Malformed request, missing required fields, or invalid field values | | `401` | `Unauthorized` | Missing or invalid credentials | | `404` | `Not Found` | Resource does not exist or caller lacks access | | `409` | `Conflict` | Concurrent or competing update to the same resource (for example, two operations racing to mutate the same loan while both appear valid in isolation) | | `422` | `Unprocessable Entity` | Request is syntactically valid but cannot be applied to the resource in its current state (for example, `POST .../decline` when `loanStatus` is not `PROPOSED`) | | `500` | `Error` | Unexpected server failure |  **State transitions vs. conflicts:** lifecycle operations (`approve`, `decline`, `cancel`, `unwind`, and similar) return **`422`** when the action is not permitted for the resource's current status. Message example: `Invalid action for current loan status`. Reserve **`409`** for true resource conflicts such as optimistic-concurrency failures when parallel clients attempt incompatible updates.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.3.1
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.api;

import java.time.OffsetDateTime;

import org.junit.Ignore;
import org.junit.Test;

import com.os.client.model.BuyinComplete;
import com.os.client.model.BuyinCompleteRequest;
import com.os.client.model.BuyinCompleteStatus;
import com.os.client.model.BuyinCompletes;
import com.os.client.model.LedgerResponse;


/**
 * API tests for BuyinsApi
 */
@Ignore
public class BuyinsApiTest {

    private final BuyinsApi api = new BuyinsApi();

    /**
     * Read a completed buyin
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerBuyinsCompletesBuyinCompleteIdGetTest() throws Exception {
        String buyinCompleteId = null;
        BuyinComplete response = api.ledgerBuyinsCompletesBuyinCompleteIdGet(buyinCompleteId);

        // TODO: test validations
    }
    /**
     * Read collection of completed buyins
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerBuyinsCompletesGetTest() throws Exception {
        OffsetDateTime since = null;
        OffsetDateTime before = null;
        Integer size = null;
        BuyinCompleteStatus buyinCompleteStatus = null;
        BuyinCompletes response = api.ledgerBuyinsCompletesGet(since, before, size, buyinCompleteStatus);

        // TODO: test validations
    }
    /**
     * Complete some or all of an initiated Buyin
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdBuyinsCompletesBuyinCompleteIdAcceptPostTest() throws Exception {
        String loanId = null;
        String buyinCompleteId = null;
        LedgerResponse response = api.ledgerLoansLoanIdBuyinsCompletesBuyinCompleteIdAcceptPost(loanId, buyinCompleteId);

        // TODO: test validations
    }
    /**
     * Read a completed Buyin
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdBuyinsCompletesBuyinCompleteIdGetTest() throws Exception {
        String loanId = null;
        String buyinCompleteId = null;
        BuyinComplete response = api.ledgerLoansLoanIdBuyinsCompletesBuyinCompleteIdGet(loanId, buyinCompleteId);

        // TODO: test validations
    }
    /**
     * Read collection of completed buyins against loan specified by &#x27;loanId&#x27;
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdBuyinsCompletesGetTest() throws Exception {
        String loanId = null;
        BuyinCompletes response = api.ledgerLoansLoanIdBuyinsCompletesGet(loanId);

        // TODO: test validations
    }
    /**
     * Complete a buyin
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdBuyinsCompletesPostTest() throws Exception {
        String loanId = null;
        BuyinCompleteRequest body = null;
        api.ledgerLoansLoanIdBuyinsCompletesPost(loanId, body);

        // TODO: test validations
    }
}
