/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.api;

import com.os.client.model.LedgerResponse;
import com.os.client.model.Loan;
import com.os.client.model.LoanProposal;
import com.os.client.model.LoanProposalApproval;
import com.os.client.model.LoanProposalCancel;
import com.os.client.model.LoanProposalCancelPending;
import com.os.client.model.LoanProposalDecline;
import com.os.client.model.LoanSplit;
import com.os.client.model.LoanSplitLot;
import com.os.client.model.LoanSplitLotAcknowledge;
import com.os.client.model.LoanStatus;
import com.os.client.model.Loans;
import com.os.client.model.LoansLoanIdBody;
import java.time.OffsetDateTime;
import com.os.client.model.Rates;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for LoansApi
 */
@Ignore
public class LoansApiTest {

    private final LoansApi api = new LoansApi();

    /**
     * Read a collection of loans. Defaults to return the last 100 loans updated.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansGetTest() throws Exception {
        OffsetDateTime since = null;
        OffsetDateTime before = null;
        Integer size = null;
        LoanStatus loanStatus = null;
        String figi = null;
        String sedol = null;
        String cusip = null;
        String ticker = null;
        String isin = null;
        String internalRefId = null;
        String partyId = null;
        String venueRefKey = null;
        Loans response = api.ledgerLoansGet(since, before, size, loanStatus, figi, sedol, cusip, ticker, isin, internalRefId, partyId, venueRefKey);

        // TODO: test validations
    }
    /**
     * Approve a loan in \&quot;proposed\&quot; state
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdApprovePostTest() throws Exception {
        LoanProposalApproval body = null;
        String loanId = null;
        LedgerResponse response = api.ledgerLoansLoanIdApprovePost(body, loanId);

        // TODO: test validations
    }
    /**
     * Cancel a loan in \&quot;proposed\&quot; state. Original proposer only.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdCancelPostTest() throws Exception {
        LoanProposalCancel body = null;
        String loanId = null;
        LedgerResponse response = api.ledgerLoansLoanIdCancelPost(body, loanId);

        // TODO: test validations
    }
    /**
     * Cancel a loan in \&quot;pending\&quot; state. Either party can initiate.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdCancelpendingPostTest() throws Exception {
        LoanProposalCancelPending body = null;
        String loanId = null;
        LedgerResponse response = api.ledgerLoansLoanIdCancelpendingPost(body, loanId);

        // TODO: test validations
    }
    /**
     * Decline a loan in \&quot;proposed\&quot; state
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdDeclinePostTest() throws Exception {
        LoanProposalDecline body = null;
        String loanId = null;
        LedgerResponse response = api.ledgerLoansLoanIdDeclinePost(body, loanId);

        // TODO: test validations
    }
    /**
     * Read a specific loan the user is authorized to access
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdGetTest() throws Exception {
        String loanId = null;
        Loan response = api.ledgerLoansLoanIdGet(loanId);

        // TODO: test validations
    }
    /**
     * Return an ordered history of this loan. Each loan has a reference event that triggered a new version.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdHistoryGetTest() throws Exception {
        String loanId = null;
        OffsetDateTime since = null;
        OffsetDateTime before = null;
        Integer size = null;
        Loans response = api.ledgerLoansLoanIdHistoryGet(loanId, since, before, size);

        // TODO: test validations
    }
    /**
     * Update unilateral fields in a loan
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdPatchTest() throws Exception {
        String loanId = null;
        LoansLoanIdBody body = null;
        LedgerResponse response = api.ledgerLoansLoanIdPatch(loanId, body);

        // TODO: test validations
    }
    /**
     * Return an ordered history of effective rate changes.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdRatehistoryGetTest() throws Exception {
        String loanId = null;
        OffsetDateTime since = null;
        OffsetDateTime before = null;
        Integer size = null;
        Rates response = api.ledgerLoansLoanIdRatehistoryGet(loanId, since, before, size);

        // TODO: test validations
    }
    /**
     * Acknowledge a loan split in \&quot;proposed\&quot; state.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdSplitLoanSplitIdAcknowledgePostTest() throws Exception {
        List<LoanSplitLotAcknowledge> body = null;
        String loanId = null;
        String loanSplitId = null;
        LedgerResponse response = api.ledgerLoansLoanIdSplitLoanSplitIdAcknowledgePost(body, loanId, loanSplitId);

        // TODO: test validations
    }
    /**
     * Retrieve a loan split.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdSplitLoanSplitIdGetTest() throws Exception {
        String loanId = null;
        String loanSplitId = null;
        LoanSplit response = api.ledgerLoansLoanIdSplitLoanSplitIdGet(loanId, loanSplitId);

        // TODO: test validations
    }
    /**
     * Split an open loan into multiple lots
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdSplitPostTest() throws Exception {
        List<LoanSplitLot> body = null;
        String loanId = null;
        LedgerResponse response = api.ledgerLoansLoanIdSplitPost(body, loanId);

        // TODO: test validations
    }
    /**
     * Create a loan in \&quot;proposal\&quot; state. Normally done by the Lend side
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansPostTest() throws Exception {
        LoanProposal body = null;
        LedgerResponse response = api.ledgerLoansPost(body);

        // TODO: test validations
    }
}
