/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.api;

import org.junit.Ignore;
import org.junit.Test;

import com.os.client.model.Parties;
import com.os.client.model.PartyType;


/**
 * API tests for PartiesApi
 */
@Ignore
public class PartiesApiTest {

    private final PartiesApi api = new PartiesApi();

    /**
     * Read a collection of registered trading parties.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerPartiesGetTest() throws Exception {
        String partyId = null;
        String partyName = null;
        String gleifLei = null;
        String internalPartyId = null;
        PartyType partyType = null;
        Parties response = api.ledgerPartiesGet(partyId, partyName, gleifLei, internalPartyId, partyType);

        // TODO: test validations
    }
}
