/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.5
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.api;

import com.os.client.model.LedgerResponse;
import com.os.client.model.Recall;
import com.os.client.model.RecallProposal;
import com.os.client.model.Recalls;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RecallsApi
 */
@Ignore
public class RecallsApiTest {

    private final RecallsApi api = new RecallsApi();

    /**
     * Read collection of recalls against contract specified by &#x27;contractId&#x27;
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerContractsContractIdRecallsGetTest() throws Exception {
        String contractId = null;
        Recalls response = api.ledgerContractsContractIdRecallsGet(contractId);

        // TODO: test validations
    }
    /**
     * Initiates a recall
     *
     * Initiates a recall notice to return securities on a contract.  ### Validation rules:   - Caller must be the lender on the contract   - &#x60;contractId&#x60; -- must reference an &#x60;OPEN&#x60; contract   - &#x60;executionVenue&#x60;     - is mandatory     - if &#x60;executionVenue.type&#x60; &#x3D;&#x3D; &#x60;ONPLATFORM&#x60; then all other elements in &#x60;executionVenue&#x60; must be null     - if &#x60;executionVenue.type&#x60; &#x3D;&#x3D; &#x60;OFFPLATFORM&#x60; then &#x60;executionVenue.partyId&#x60;, &#x60;executionVenue.venueName&#x60;, and &#x60;executionVenue.partyRole&#x60; are mandatory   - &#x60;quantity&#x60;     - is mandatory     - must be &lt; 0     - must be &lt;&#x3D; contract open quantity - all existing open recall quantities   - &#x60;recallDate&#x60;     - is mandatory     - must be &gt;&#x3D; current day   - &#x60;recallDueDate&#x60;     - is mandatory     - must be &gt; &#x60;recallDate&#x60; 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerContractsContractIdRecallsPostTest() throws Exception {
        RecallProposal body = null;
        String contractId = null;
        api.ledgerContractsContractIdRecallsPost(body, contractId);

        // TODO: test validations
    }
    /**
     * Cancel a recall in \&quot;proposed\&quot; state. Original proposer only.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerContractsContractIdRecallsRecallIdCancelPostTest() throws Exception {
        String contractId = null;
        String recallId = null;
        LedgerResponse response = api.ledgerContractsContractIdRecallsRecallIdCancelPost(contractId, recallId);

        // TODO: test validations
    }
    /**
     * Read a recall
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerContractsContractIdRecallsRecallIdGetTest() throws Exception {
        String contractId = null;
        String recallId = null;
        Recall response = api.ledgerContractsContractIdRecallsRecallIdGet(contractId, recallId);

        // TODO: test validations
    }
    /**
     * Cancel a recall in \&quot;proposed\&quot; state. Original proposer only.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerContractsContractIdRecallsRecallIdVenuecancelPostTest() throws Exception {
        String contractId = null;
        String recallId = null;
        LedgerResponse response = api.ledgerContractsContractIdRecallsRecallIdVenuecancelPost(contractId, recallId);

        // TODO: test validations
    }
    /**
     * For delegated venues to create a recall atomically
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerContractsContractIdVenuerecallsPostTest() throws Exception {
        RecallProposal body = null;
        String contractId = null;
        api.ledgerContractsContractIdVenuerecallsPost(body, contractId);

        // TODO: test validations
    }
    /**
     * Read collection of recalls
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerRecallsGetTest() throws Exception {
        Recalls response = api.ledgerRecallsGet();

        // TODO: test validations
    }
    /**
     * Read a recall
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerRecallsRecallIdGetTest() throws Exception {
        String recallId = null;
        Recall response = api.ledgerRecallsRecallIdGet(recallId);

        // TODO: test validations
    }
}
