/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.   ### HTTP status codes  All error responses use the `LedgerResponse` envelope (`code`, `type`, `message`, `responseDateTime`, optional `resourceUri`).  | Status | `type` | When | |--------|--------|------| | `400` | `Bad Request` | Malformed request, missing required fields, or invalid field values | | `401` | `Unauthorized` | Missing or invalid credentials | | `404` | `Not Found` | Resource does not exist or caller lacks access | | `409` | `Conflict` | Concurrent or competing update to the same resource (for example, two operations racing to mutate the same loan while both appear valid in isolation) | | `422` | `Unprocessable Entity` | Request is syntactically valid but cannot be applied to the resource in its current state (for example, `POST .../decline` when `loanStatus` is not `PROPOSED`) | | `500` | `Error` | Unexpected server failure |  **State transitions vs. conflicts:** lifecycle operations (`approve`, `decline`, `cancel`, `unwind`, and similar) return **`422`** when the action is not permitted for the resource's current status. Message example: `Invalid action for current loan status`. Reserve **`409`** for true resource conflicts such as optimistic-concurrency failures when parallel clients attempt incompatible updates.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.3.1
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.client.api;

import java.time.OffsetDateTime;

import org.junit.Ignore;
import org.junit.Test;

import com.os.client.model.LedgerResponse;
import com.os.client.model.ModelReturn;
import com.os.client.model.ReturnAcknowledgement;
import com.os.client.model.ReturnProposal;
import com.os.client.model.ReturnSortField;
import com.os.client.model.ReturnStatus;
import com.os.client.model.Returns;
import com.os.client.model.ReturnsReturnIdBody;
import com.os.client.model.SortOrder;


/**
 * API tests for ReturnsApi
 */
@Ignore
public class ReturnsApiTest {

    private final ReturnsApi api = new ReturnsApi();

    /**
     * Read collection of returns against loan specified by &#x27;loanId&#x27;
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsGetTest() throws Exception {
        String loanId = null;
        OffsetDateTime since = null;
        OffsetDateTime before = null;
        Integer size = null;
        ReturnStatus returnStatus = null;
        SortOrder sortOrder = null;
        ReturnSortField sortField = null;
        Returns response = api.ledgerLoansLoanIdReturnsGet(loanId, since, before, size, returnStatus, sortOrder, sortField);

        // TODO: test validations
    }
    /**
     * Create a return
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsPostTest() throws Exception {
        ReturnProposal body = null;
        String loanId = null;
        api.ledgerLoansLoanIdReturnsPost(body, loanId);

        // TODO: test validations
    }
    /**
     * Acknowledge a pending return. No change to status.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsReturnIdAcknowledgePostTest() throws Exception {
        ReturnAcknowledgement body = null;
        String loanId = null;
        String returnId = null;
        LedgerResponse response = api.ledgerLoansLoanIdReturnsReturnIdAcknowledgePost(body, loanId, returnId);

        // TODO: test validations
    }
    /**
     * Cancel a return in \&quot;proposed\&quot; or \&quot;pending\&quot; state. Original proposer only.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsReturnIdCancelPostTest() throws Exception {
        String loanId = null;
        String returnId = null;
        LedgerResponse response = api.ledgerLoansLoanIdReturnsReturnIdCancelPost(loanId, returnId);

        // TODO: test validations
    }
    /**
     * Read a return
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsReturnIdGetTest() throws Exception {
        String loanId = null;
        String returnId = null;
        ModelReturn response = api.ledgerLoansLoanIdReturnsReturnIdGet(loanId, returnId);

        // TODO: test validations
    }
    /**
     * Update unilateral fields on a return
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsReturnIdPatchTest() throws Exception {
        String loanId = null;
        String returnId = null;
        ReturnsReturnIdBody body = null;
        LedgerResponse response = api.ledgerLoansLoanIdReturnsReturnIdPatch(loanId, returnId, body);

        // TODO: test validations
    }
    /**
     * Approve the unwind of a return in &#x27;settled&#x27; state.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsReturnIdUnwindApprovePostTest() throws Exception {
        String loanId = null;
        String returnId = null;
        LedgerResponse response = api.ledgerLoansLoanIdReturnsReturnIdUnwindApprovePost(loanId, returnId);

        // TODO: test validations
    }
    /**
     * Cancel the unwind of a return in &#x27;settled&#x27; state.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsReturnIdUnwindCancelPostTest() throws Exception {
        String loanId = null;
        String returnId = null;
        LedgerResponse response = api.ledgerLoansLoanIdReturnsReturnIdUnwindCancelPost(loanId, returnId);

        // TODO: test validations
    }
    /**
     * Decline the unwind of a return in &#x27;settled&#x27; state.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsReturnIdUnwindDeclinePostTest() throws Exception {
        String loanId = null;
        String returnId = null;
        LedgerResponse response = api.ledgerLoansLoanIdReturnsReturnIdUnwindDeclinePost(loanId, returnId);

        // TODO: test validations
    }
    /**
     * Unwind/close a return that settled on the current date. Either party can initiate.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerLoansLoanIdReturnsReturnIdUnwindPostTest() throws Exception {
        String loanId = null;
        String returnId = null;
        LedgerResponse response = api.ledgerLoansLoanIdReturnsReturnIdUnwindPost(loanId, returnId);

        // TODO: test validations
    }
    /**
     * Read collection of returns
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerReturnsGetTest() throws Exception {
        OffsetDateTime since = null;
        OffsetDateTime before = null;
        Integer size = null;
        ReturnStatus returnStatus = null;
        SortOrder sortOrder = null;
        ReturnSortField sortField = null;
        Returns response = api.ledgerReturnsGet(since, before, size, returnStatus, sortOrder, sortField);

        // TODO: test validations
    }
    /**
     * Read a return
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ledgerReturnsReturnIdGetTest() throws Exception {
        String returnId = null;
        ModelReturn response = api.ledgerReturnsReturnIdGet(returnId);

        // TODO: test validations
    }
}
